package profiles

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/GreyhavenHQ/greywall/internal/config"
)

// DriftAction is the action the user chose when prompted about a drifted profile.
type DriftAction int

const (
	// ActionSkip keeps the learned profile as-is for this run only. Re-prompts
	// on the next run as long as the drift persists.
	ActionSkip DriftAction = iota
	// ActionMerge merges bundled under learned and rewrites the file.
	// Merge is union-based: it only adds bundled entries, never removes user
	// customizations.
	ActionMerge
	// ActionKeep keeps the learned profile as-is and stamps the current drift
	// hash so the prompt does not reappear until the bundled profile drifts
	// to a different delta.
	ActionKeep
)

// isInteractiveDrift returns true if both stdin and stderr are terminals and
// the user has not opted out via GREYWALL_NO_PROMPT.
func isInteractiveDrift() bool {
	if os.Getenv("GREYWALL_NO_PROMPT") != "" {
		return false
	}
	return isTerminal(os.Stdin) && isTerminal(os.Stderr)
}

// PromptDriftResolution asks the user how to resolve profile drift. Returns
// ActionKeep on any non-interactive condition, EOF, or unrecognized input.
// Writes the prompt to stderr and reads from stdin.
//
// learned and bundled are used to render diffs when the user picks [d].
func PromptDriftResolution(info DriftInfo, learned, bundled *config.Config) DriftAction {
	if !info.HasDrift || !isInteractiveDrift() {
		return ActionSkip
	}
	return promptDriftResolution(info, learned, bundled, os.Stdin, os.Stderr)
}

// promptDriftResolution is the testable core; it does not consult the environment.
//
//nolint:errcheck,gosec // terminal UI output, errors are non-actionable
func promptDriftResolution(info DriftInfo, learned, bundled *config.Config, in io.Reader, out io.Writer) DriftAction {
	fmt.Fprintf(out, "\n[greywall:profile] Bundled profile %q has been updated since your learned file was generated.\n", info.CmdName)
	switch info.Reason {
	case DriftMissingStamp:
		fmt.Fprintf(out, "[greywall:profile]   Your learned file has no version stamp (predates greywall %s).\n", info.RunningVersion)
	case DriftSchema:
		fmt.Fprintf(out, "[greywall:profile]   Learned schema v%d is older than current schema v%d.\n", info.LearnedSchema, info.RunningSchema)
	case DriftVersion:
		fmt.Fprintf(out, "[greywall:profile]   Learned generated by greywall %s, running %s.\n", info.LearnedVersion, info.RunningVersion)
	case DriftContent:
		fmt.Fprintln(out, "[greywall:profile]   Bundled profile has entries not present in your learned file.")
	}

	renderDriftDiffs(out, learned, bundled)

	fmt.Fprintln(out, "[greywall:profile]")
	fmt.Fprintln(out, "[greywall:profile]   [m] merge the template into my version (rewrites file, keeps .bak) (default)")
	fmt.Fprintln(out, "[greywall:profile]   [k] keep my version (don't ask again unless template changes)")
	fmt.Fprintln(out, "[greywall:profile]   [i] ignore just this time (ask again next run)")
	fmt.Fprint(out, "[greywall:profile] Choice [m]: ")

	reader := bufio.NewReader(in)
	line, err := reader.ReadString('\n')
	if err != nil && line == "" {
		fmt.Fprintln(out)
		return ActionMerge
	}
	line = strings.ToLower(strings.TrimSpace(line))
	if line == "" {
		return ActionMerge
	}
	switch line[0] {
	case 'k':
		return ActionKeep
	case 'i':
		return ActionSkip
	default:
		return ActionMerge
	}
}

// renderDriftDiffs prints the additions merge would make to the learned config.
//
//nolint:errcheck,gosec // terminal UI output, errors are non-actionable
func renderDriftDiffs(out io.Writer, learned, bundled *config.Config) {
	if learned == nil || bundled == nil {
		fmt.Fprintln(out, "[greywall:profile]   (diff unavailable: missing profile data)")
		return
	}
	merged := config.Merge(bundled, learned)

	mergeDiff := DiffConfigs(learned, merged)
	fmt.Fprintln(out, "[greywall:profile]")
	fmt.Fprintln(out, "[greywall:profile] === [m] merge would add:")
	if mergeDiff == "" {
		fmt.Fprintln(out, "[greywall:profile]   (nothing to add)")
	} else {
		for _, l := range strings.Split(strings.TrimRight(mergeDiff, "\n"), "\n") {
			fmt.Fprintf(out, "[greywall:profile] %s\n", l)
		}
	}
}
